name: CI

on:
  push:
    branches: [main] # Change to your default branch if different
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version compatible with your project
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Build Next.js project
        run: npm run build

      - name: Run tests
        run: npm test
